version: '2.3'
services:
  geotrellis-gdal:
    image: quay.io/azavea/openjdk-gdal:2.3.2-jdk8-slim
    environment:
      - BINTRAY_USER=$BINTRAY_USER
      - BINTRAY_PASS=$BINTRAY_PASS
    volumes:
      - ${TRAVIS_BUILD_DIR:-./}:/opt/geotrellis-gdal
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
      - $HOME/.coursier:/root/.coursier
    working_dir: /opt/geotrellis-gdal
    entrypoint: ./sbt "++${SCALA_VERSION:-2.11.12}"
